package com.isep.metier;
// Generated 31 mai 2016 12:01:41 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Assignements generated by hbm2java
 */
public class Assignements implements java.io.Serializable {

	private Integer idAssignements;
	private Date dueTime;
	private Date createdTime;
	private String description;
	private Set groupeses = new HashSet(0);

	public Assignements() {
	}

	public Assignements(Date dueTime, Date createdTime, String description, Set groupeses) {
		this.dueTime = dueTime;
		this.createdTime = createdTime;
		this.description = description;
		this.groupeses = groupeses;
	}

	public Integer getIdAssignements() {
		return this.idAssignements;
	}

	public void setIdAssignements(Integer idAssignements) {
		this.idAssignements = idAssignements;
	}

	public Date getDueTime() {
		return this.dueTime;
	}

	public void setDueTime(Date dueTime) {
		this.dueTime = dueTime;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getGroupeses() {
		return this.groupeses;
	}

	public void setGroupeses(Set groupeses) {
		this.groupeses = groupeses;
	}

}
