package com.isep.metier;
// Generated 31 mai 2016 12:01:41 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
 

/**
 * Competences generated by hbm2java
 */
public class Competences implements java.io.Serializable {

	private Integer idCompetences;
	private Famillecompetences famillecompetences;
	private String libelle;
	private Set noteses = new HashSet(0);

	public Competences() {
	}

	public Competences(Famillecompetences famillecompetences) {
		this.famillecompetences = famillecompetences;
	}

	public Competences(Famillecompetences famillecompetences, String libelle, Set noteses) {
		this.famillecompetences = famillecompetences;
		this.libelle = libelle;
		this.noteses = noteses;
	}

	public Integer getIdCompetences() {
		return this.idCompetences;
	}

	public void setIdCompetences(Integer idCompetences) {
		this.idCompetences = idCompetences;
	}

	public Famillecompetences getFamillecompetences() {
		return this.famillecompetences;
	}

	public void setFamillecompetences(Famillecompetences famillecompetences) {
		this.famillecompetences = famillecompetences;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set getNoteses() {
		return this.noteses;
	}

	public void setNoteses(Set noteses) {
		this.noteses = noteses;
	}

}
