package com.isep.metier;
// Generated 31 mai 2016 12:01:41 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Competencesgrp generated by hbm2java
 */
public class Competencesgrp implements java.io.Serializable {

	private Integer idCompetencesGrp;
	private Famillecompetencesgrp famillecompetencesgrp;
	private String libelle;
	private Set remarqueses = new HashSet(0);

	public Competencesgrp() {
	}

	public Competencesgrp(Famillecompetencesgrp famillecompetencesgrp) {
		this.famillecompetencesgrp = famillecompetencesgrp;
	}

	public Competencesgrp(Famillecompetencesgrp famillecompetencesgrp, String libelle, Set remarqueses) {
		this.famillecompetencesgrp = famillecompetencesgrp;
		this.libelle = libelle;
		this.remarqueses = remarqueses;
	}

	public Integer getIdCompetencesGrp() {
		return this.idCompetencesGrp;
	}

	public void setIdCompetencesGrp(Integer idCompetencesGrp) {
		this.idCompetencesGrp = idCompetencesGrp;
	}

	public Famillecompetencesgrp getFamillecompetencesgrp() {
		return this.famillecompetencesgrp;
	}

	public void setFamillecompetencesgrp(Famillecompetencesgrp famillecompetencesgrp) {
		this.famillecompetencesgrp = famillecompetencesgrp;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set getRemarqueses() {
		return this.remarqueses;
	}

	public void setRemarqueses(Set remarqueses) {
		this.remarqueses = remarqueses;
	}

}
