package com.isep.metier;
// Generated 31 mai 2016 12:01:41 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Groupes generated by hbm2java
 */
public class Groupes implements java.io.Serializable {

	private Integer idGroupes;
    private String emailtuteur;

	private Set assignementses = new HashSet(0);
	private Set userses = new HashSet(0);
	private Set remarqueses = new HashSet(0);

	public Groupes() {
	}

	public Groupes(int idGroupes,String emailtuteur, Set assignementses, Set userses, Set remarqueses) {
		this.idGroupes=idGroupes;
		this.emailtuteur=emailtuteur;
		this.assignementses = assignementses;
		this.userses = userses;
		this.remarqueses = remarqueses;
	}

	public String getEmailtuteur() {
		return emailtuteur;
	}

	public void setEmailtuteur(String emailtuteur) {
		this.emailtuteur = emailtuteur;
	}

	public Integer getIdGroupes() {
		return this.idGroupes;
	}

	public void setIdGroupes(Integer idGroupes) {
		this.idGroupes = idGroupes;
	}


	public Set getAssignementses() {
		return this.assignementses;
	}

	public void setAssignementses(Set assignementses) {
		this.assignementses = assignementses;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

	public Set getRemarqueses() {
		return this.remarqueses;
	}

	public void setRemarqueses(Set remarqueses) {
		this.remarqueses = remarqueses;
	}

}
