package com.isep.metier;
// Generated 31 mai 2016 12:01:41 by Hibernate Tools 5.1.0.Alpha1

/**
 * Notes generated by hbm2java
 */
public class Notes implements java.io.Serializable {

	private NotesId id;
	private Competences competences;
	private Users users;
	private Float note;
	private String remarques;

	public Notes() {
	}

	public Notes(NotesId id, Competences competences, Users users) {
		this.id = id;
		this.competences = competences;
		this.users = users;
	}

	public Notes(NotesId id, Competences competences, Users users, Float note, String remarques) {
		this.id = id;
		this.competences = competences;
		this.users = users;
		this.note = note;
		this.remarques = remarques;
	}

	public NotesId getId() {
		return this.id;
	}

	public void setId(NotesId id) {
		this.id = id;
	}

	public Competences getCompetences() {
		return this.competences;
	}

	public void setCompetences(Competences competences) {
		this.competences = competences;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Float getNote() {
		return this.note;
	}

	public void setNote(Float note) {
		this.note = note;
	}

	public String getRemarques() {
		return this.remarques;
	}

	public void setRemarques(String remarques) {
		this.remarques = remarques;
	}

}
