package com.isep.metier;
// Generated 31 mai 2016 12:01:41 by Hibernate Tools 5.1.0.Alpha1

/**
 * RemarquesId generated by hbm2java
 */
public class RemarquesId implements java.io.Serializable {

	private int idRemarques;
	private int competencesGrpIdCompetencesGrp;
	private int groupesIdGroupes;

	public RemarquesId() {
	}

	public RemarquesId(int idRemarques, int competencesGrpIdCompetencesGrp, int groupesIdGroupes) {
		this.idRemarques = idRemarques;
		this.competencesGrpIdCompetencesGrp = competencesGrpIdCompetencesGrp;
		this.groupesIdGroupes = groupesIdGroupes;
	}

	public int getIdRemarques() {
		return this.idRemarques;
	}

	public void setIdRemarques(int idRemarques) {
		this.idRemarques = idRemarques;
	}

	public int getCompetencesGrpIdCompetencesGrp() {
		return this.competencesGrpIdCompetencesGrp;
	}

	public void setCompetencesGrpIdCompetencesGrp(int competencesGrpIdCompetencesGrp) {
		this.competencesGrpIdCompetencesGrp = competencesGrpIdCompetencesGrp;
	}

	public int getGroupesIdGroupes() {
		return this.groupesIdGroupes;
	}

	public void setGroupesIdGroupes(int groupesIdGroupes) {
		this.groupesIdGroupes = groupesIdGroupes;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RemarquesId))
			return false;
		RemarquesId castOther = (RemarquesId) other;

		return (this.getIdRemarques() == castOther.getIdRemarques())
				&& (this.getCompetencesGrpIdCompetencesGrp() == castOther.getCompetencesGrpIdCompetencesGrp())
				&& (this.getGroupesIdGroupes() == castOther.getGroupesIdGroupes());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRemarques();
		result = 37 * result + this.getCompetencesGrpIdCompetencesGrp();
		result = 37 * result + this.getGroupesIdGroupes();
		return result;
	}

}
