package com.isep.metier;
// Generated 31 mai 2016 12:01:41 by Hibernate Tools 5.1.0.Alpha1

/**
 * Remarques generated by hbm2java
 */
public class Remarques implements java.io.Serializable {

	private RemarquesId id;
	private Competencesgrp competencesgrp;
	private Groupes groupes;
	private String remarque;

	public Remarques() {
	}

	public Remarques(RemarquesId id, Competencesgrp competencesgrp, Groupes groupes) {
		this.id = id;
		this.competencesgrp = competencesgrp;
		this.groupes = groupes;
	}

	public Remarques(RemarquesId id, Competencesgrp competencesgrp, Groupes groupes, String remarque) {
		this.id = id;
		this.competencesgrp = competencesgrp;
		this.groupes = groupes;
		this.remarque = remarque;
	}

	public RemarquesId getId() {
		return this.id;
	}

	public void setId(RemarquesId id) {
		this.id = id;
	}

	public Competencesgrp getCompetencesgrp() {
		return this.competencesgrp;
	}

	public void setCompetencesgrp(Competencesgrp competencesgrp) {
		this.competencesgrp = competencesgrp;
	}

	public Groupes getGroupes() {
		return this.groupes;
	}

	public void setGroupes(Groupes groupes) {
		this.groupes = groupes;
	}

	public String getRemarque() {
		return this.remarque;
	}

	public void setRemarque(String remarque) {
		this.remarque = remarque;
	}

}
