package com.isep.metier;
// Generated 31 mai 2016 12:01:41 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer idUsers;
	private Groupes groupes;
	private String username;
	private String password;
	private String email;
	private String rights;
	private Set noteses = new HashSet(0);
	private Set absenceses = new HashSet(0);
	private String prenom;
	private String nom;

	public Users() {
	}

	public Users(Groupes groupes, String username, String password, String email, String rights, Set noteses,
			Set absenceses, String nom, String prenom) {
		this.groupes = groupes;
		this.username = username;
		this.password = password;
		this.email = email;
		this.rights = rights;
		this.noteses = noteses;
		this.absenceses = absenceses;
		this.nom=nom;
		this.prenom=prenom;
	}

	public Integer getIdUsers() {
		return idUsers;
	}

	public void setIdUsers(Integer idUsers) {
		this.idUsers = idUsers;
	}

	public Groupes getGroupes() {
		return groupes;
	}

	public void setGroupes(Groupes groupes) {
		this.groupes = groupes;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRights() {
		return rights;
	}

	public void setRights(String rights) {
		this.rights = rights;
	}

	public Set getNoteses() {
		return noteses;
	}

	public void setNoteses(Set noteses) {
		this.noteses = noteses;
	}

	public Set getAbsenceses() {
		return absenceses;
	}

	public void setAbsenceses(Set absenceses) {
		this.absenceses = absenceses;
	}
	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
}
